/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test
    void test() {
        QuotesClass quotesClass = new QuotesClass();
        quotesClass.quotes("/mnt/c/Users/M.2070/MyWork/quotes/app/src/main/resources/Data.json");
    }
}
